/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_siddhi_extension_var_realtime_montecarlo_MonteCarloNativeSimulation */

#ifndef _Included_org_wso2_siddhi_extension_var_realtime_montecarlo_MonteCarloNativeSimulation
#define _Included_org_wso2_siddhi_extension_var_realtime_montecarlo_MonteCarloNativeSimulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wso2_siddhi_extension_var_realtime_montecarlo_MonteCarloNativeSimulation
 * Method:    simulation
 * Signature: (DDDDII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_wso2_siddhi_extension_var_realtime_montecarlo_MonteCarloNativeSimulation_simulation
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
